name: bybit_card_tracker
description: "Bybit Card expense tracker & analytics app."
publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
